name: CI-CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2

  ECR_REGISTRY: 095355901466.dkr.ecr.ap-southeast-2.amazonaws.com
  ECR_REPOSITORY: shopping-agent

  ECS_CLUSTER: shopping-agent-cluster
  ECS_SERVICE: shopping-agent-service

  IMAGE_TAG: latest

permissions:
  contents: read


jobs:

  security-scan:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Scan filesystem with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 0


  build-and-push:
    name: Build Docker Image and Push to ECR
    needs: security-scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
          -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Tag image for ECR
        run: |
          docker tag \
          $ECR_REPOSITORY:$IMAGE_TAG \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push image to ECR
        run: |
          docker push \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


  deploy:

    name: Deploy to ECS Fargate
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy new ECS version
        run: |
          aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment

      - name: Wait for ECS deployment
        run: |
          aws ecs wait services-stable \
          --cluster $ECS_CLUSTER \
          --services $ECS_SERVICE
